---
title: 'Lab 2 Report: TV watching across generations'
author: "Godsee Joy, Karanveer Lamba, Deric Liang"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---

\vspace{-5truemm}

```{r, warning = FALSE, message = FALSE}
# Clear environment
rm(list = ls())

# Set seed
set.seed(23948729)

# Import libraries
library(tidyverse)
library(readxl)
library(ggpubr)
library(lmtest)
library(sandwich)
library(data.table)
library(stargazer)
```

```{r, warning = F}
# Read data
# gss_df_raw <- read_excel("GSS.xlsx", sheet = "Data")
gss_df_raw <- fread("GSSv3.csv")

# Clean variables
gss_df <- gss_df_raw %>%
  mutate(age = as.numeric(case_when(age == "89 or older" ~ "89",
                                    age == ".n: No answer" ~ NA,
                                    T ~ age)),
         age_cat = relevel(as.factor(case_when(age >= 18 & age < 38 ~ "Gen Z / Millenial",
                             age >= 38 & age < 54 ~ "Gen X",
                             age >= 54 & age < 73 ~ "Baby Boomer",
                             age >= 73 ~ "Silent Generation")), ref = "Gen Z / Millenial"),
         tvhours = as.numeric(case_when(grepl("\\.", tvhours) ~ NA,
                                        tvhours == "0 hours" ~ "0",
                                        tvhours == "24 hours" ~ "24",
                                        T ~ tvhours)),
         marital = relevel(as.factor(case_when(grepl("\\.", marital) ~ NA,
                             marital == "Married" ~ "Married",
                             T ~ "Not married")), ref = "Married"),
         wrkstat = relevel(as.factor(case_when(grepl("\\.", wrkstat) ~ NA,
                             grepl("Working", wrkstat) ~ "Working",
                             T ~ "Not working")), ref = "Working"),
         degree = relevel(as.factor(degree), ref = "Graduate"),
         hompop = as.numeric(hompop),
         coninc = as.numeric(coninc),
         coninc = case_when(coninc < 0 ~ NA,
                            T ~ coninc)) %>%
  select(wrkstat, marital, age, degree, sex, hompop, tvhours, coninc, age_cat) %>%
  drop_na()

# Train/test datasets
smp_size = floor(0.3 * nrow(gss_df))
train_ind <- sample(seq_len(nrow(gss_df)), size = smp_size)
gss_df_train <- gss_df[train_ind,]
gss_df_test <- gss_df[-train_ind,]
```

```{r, message = FALSE}
# Histogram for age and tv hours
age_plot <- gss_df %>%
  ggplot(aes(x = age)) +
  geom_histogram() +
  labs(x = "Age", y = "Frequency", title = "Distribution of age")
inc_plot <- gss_df %>%
  ggplot(aes(x = coninc)) +
  geom_histogram() +
  labs(x = "Income", y = "Frequency", title = "Distribution of income")
tv_plot <- gss_df %>%
  ggplot(aes(x = tvhours)) +
  geom_histogram() +
  labs(x = "Hours of TV watched per day", y = "Frequency", 
       title = "Distribution of TV hrs per day")
ggarrange(tv_plot, inc_plot, ncol = 1, nrow = 2)
```

```{r}
# Facet graph of tv hours versus all covariates
tv_age_plot <- gss_df %>%
  ggplot(aes(x = reorder(age_cat, tvhours), y = tvhours)) +
  geom_boxplot() +
  labs(x = "Age", y = "TV hrs", title = "TV hrs vs. age") +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))
tv_educ_plot <- gss_df %>%
  ggplot(aes(x = reorder(degree, -tvhours), y = tvhours)) +
  geom_boxplot() +
  labs(x = "Highest level of education", y = "TV hrs", title = "TV hrs vs. education") +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = .9))
tv_wrk_plot <- gss_df %>%
  drop_na(wrkstat) %>%
  ggplot(aes(x = reorder(wrkstat, -tvhours), y = tvhours)) +
  geom_boxplot() +
  labs(x = "Employment status", y = "TV hrs", title = "TV hrs vs. employment") +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))
tv_marital_plot <- gss_df %>%
  drop_na(wrkstat) %>%
  ggplot(aes(x = reorder(marital, -tvhours), y = tvhours)) +
  geom_boxplot() +
  labs(x = "Marital status", y = "TV hrs", title = "TV hrs vs. marital status") +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))
```

```{r}
# Plot age
tv_age_plot
```

```{r}
# Plot first two figures
ggarrange(tv_wrk_plot, tv_marital_plot, ncol = 2, nrow = 1)
```

```{r}
tv_inc_plot <- gss_df_train %>%
  ggplot(aes(x = log(coninc), y = tvhours)) +
  geom_jitter() +
  geom_smooth(method = lm, se = TRUE) +
  labs(x = "Income", y = "TV hours", title = "TV hours vs. income")
```

```{r}
# Plot last two figures
ggarrange(tv_educ_plot, tv_inc_plot, ncol = 2, nrow = 1)
```

```{r}
tv_hh_plot <- gss_df_train %>%
  ggplot(aes(x = hompop, y = tvhours, color = age_cat)) +
  geom_jitter() +
  geom_smooth(method = lm, se = F) +
  labs(x = "hh size", y = "TV hours", title = "TV hours vs. hh size")
tv_hh_plot
```

```{r, results = "asis"}
# Basic model
mod1 <- lm(tvhours ~ age, data = gss_df_test)
mod2 <- lm(tvhours ~ age_cat, data = gss_df_test)
mod3 <- lm(tvhours ~ age_cat + wrkstat, data = gss_df_test)
mod4 <- lm(tvhours ~ age_cat + wrkstat + marital, data = gss_df_test)
mod5 <- lm(tvhours ~ age_cat + wrkstat + marital + degree, data = gss_df_test)

# Full model with robust SE
tv_mod <- lm(tvhours ~ age_cat + wrkstat + marital + degree + log(coninc), data = gss_df_test)

# RSEs
rse1 <- sqrt(diag(vcovHC(mod1)))
rse2 <- sqrt(diag(vcovHC(mod2)))
rse3 <- sqrt(diag(vcovHC(mod3)))
rse4 <- sqrt(diag(vcovHC(mod4)))
rse5 <- sqrt(diag(vcovHC(mod5)))
rse6 <- sqrt(diag(vcovHC(tv_mod)))

# Stargazer
stargazer(mod1, mod2, mod3, mod4, mod5, tv_mod,
          se = list(rse1, rse2, rse3, rse4, rse5, rse6), 
          title = "Regression models for age on TV hours per day",
          dep.var.labels = "TV hours",
          covariate.labels = c("Age", "Generation-Baby Boomer", "Generation-Gen X",
                               "Generation-Silent", "Not working", "Not married", 
                               "Education-Associate", "Education-Bachelor", "Education-High School",
                               "Education-Less than High School", "ln(Income)"),
          omit.stat=c("f", "ser"),
          column.sep.width = "-5pt",
          header = FALSE, no.space = TRUE)
```



